src/Aliquota.Presentation/Controllers/ApplicationsController.cs
using Aliquota.Application.Interfaces;
using Aliquota.Application.ViewModels;
using Aliquota.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aliquota.Presentation.Controllers
{
    public class ApplicationsController : Controller
    {
        private readonly IApplicationAppService _applicationAppService;
        private readonly IApplicationRepository _applicationRepository;
        public ApplicationsController(IApplicationAppService applicationAppService,
                                        IApplicationRepository applicationRepository)
        {
            _applicationAppService = applicationAppService;
            _applicationRepository = applicationRepository;
        }
        public async Task<IActionResult> Index()
        {
            var applicationsViewModel = await _applicationAppService.ListApplicationsAsync();
            return View(applicationsViewModel);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var edit = await _applicationRepository.UpdateApplication(id);

            return View(edit);
        }
    }
}

src/Aliquota.Presentation/Views/Applications/Edit.cshtml
@model Aliquota.Domain.Models.Application

@{
    ViewData["Title"] = "Edit";
}

<h1>Retirar Aplicação</h1>

<div>
    <h4>Dados da Aplicação</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CurrentValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithdrawnAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithdrawnAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithdrawValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithdrawValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

src/Aliquota.Presentation/Views/Applications/Index.cshtml
@model IEnumerable<Aliquota.Application.ViewModels.ApplicationViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Minhas Aplicações</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentValue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentValue)
            </td>
            <td>
                @Html.ActionLink("Retirar Valor", "Edit", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

src/Aliquota.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kinvo Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aliquota.Presentation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Minhas Aplicações</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Aliquota.Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>